In [199]:
import pandas as pd
import numpy as np
import matplotlib .pyplot as plt
import matplotlib.image as mpimg

In [200]:
import cv2 
import os 
import glob 
img_dir = r"C:\Users\Umar\image1" # Enter Directory of all images  
data_path = os.path.join(img_dir,'*g') 
files = glob.glob(data_path) 
data = [] 
for f1 in files: 
    img = cv2.imread(f1) 
    img.resize((200,200))
    data.append(img) 

In [201]:
import cv2 
import os 
import glob 
img_dirsss = r"C:\Users\Umar\male" # Enter Directory of all images  
data_pathsss = os.path.join(img_dirsss,'*g') 
filessss = glob.glob(data_pathsss) 
data11 = [] 
for f1sss in filessss: 
    imgsss = cv2.imread(f1sss) 
    imgsss.resize((200,200))
    data11.append(imgsss) 

In [202]:
import cv2 
import os 
import glob 
img_dirs = r"C:\Users\Umar\image2" # Enter Directory of all images  
data_paths = os.path.join(img_dirs,'*g') 
filess = glob.glob(data_paths) 
data1 = [] 
for f1s in filess: 
    imgs = cv2.imread(f1s) 
    imgs.resize((200,200))
    data1.append(imgs) 

In [203]:
data

[array([[ 57,  57,  57, ...,  67,  61,  58],
        [ 67,  61,  58, ...,  61,  70,  64],
        [ 61,  70,  64, ...,  62,  60,  66],
        ...,
        [ 68,  77,  71, ...,  76,  74,  80],
        [ 76,  75,  79, ..., 168,  67,  98],
        [151,  48,  74, ...,  71,  77,  73]], dtype=uint8),
 array([[  0,   2,  29, ..., 245, 112, 231],
        [255,  85, 222, ...,   6,  31,   1],
        [  6,  31,   2, ...,   8,   5,  27],
        ...,
        [ 35,  70,  19, ...,  31,  45,  63],
        [ 30,  44,  63, ...,  82,  34,  56],
        [ 81,  27,  54, ..., 178, 231, 133]], dtype=uint8),
 array([[ 12,  45,  30, ..., 114,  72, 104],
        [127,  79, 109, ..., 167, 136, 168],
        [151, 124, 191, ...,  63, 133, 103],
        ...,
        [ 18,  16,  35, ..., 235, 238, 253],
        [236, 239, 254, ...,  95,  49, 121],
        [ 98,  49, 123, ...,  77,  53,  51]], dtype=uint8),
 array([[253, 253, 253, ...,  38,  40,  34],
        [ 35,  22,  16, ...,  44,  65,  98],
        [ 83, 10

In [204]:
data1

[array([[ 87, 101, 130, ...,  79, 101, 103],
        [104,  90,  92, ..., 113, 119, 141],
        [141, 147, 143, ...,  85,  98, 130],
        ...,
        [  3,   9,   1, ..., 139, 159, 206],
        [143, 161, 208, ...,   7,   5,   6],
        [  4,   0,   1, ..., 141, 177, 124]], dtype=uint8),
 array([[150, 178, 189, ..., 202, 168, 196],
        [203, 168, 196, ...,  36,  41,  81],
        [ 87,  92,  24, ..., 106, 159, 186],
        ...,
        [196, 207, 168, ..., 177, 205, 212],
        [177, 206, 211, ..., 182, 125, 143],
        [172, 125, 145, ..., 172, 194, 125]], dtype=uint8),
 array([[105, 143, 121, ...,  15,  21,  16],
        [ 15,  20,  15, ...,  15,  13,  15],
        [ 16,  14,  15, ...,  78, 100,  71],
        ...,
        [ 14,  13,  15, ...,  89, 111,  87],
        [ 87, 111,  87, ..., 229, 190, 212],
        [230, 191, 213, ...,  18,  10,  18]], dtype=uint8),
 array([[102, 141, 143, ...,  74,  62,  79],
        [ 75,  63,  80, ..., 135, 130, 102],
        [134, 12

In [205]:
data11

[array([[22, 30, 29, ..., 28, 31, 29],
        [28, 31, 29, ..., 40, 41, 32],
        [36, 37, 30, ..., 20, 20, 20],
        ...,
        [27, 27, 29, ..., 62, 69, 72],
        [67, 74, 77, ..., 52, 38, 43],
        [52, 37, 42, ..., 69, 80, 65]], dtype=uint8),
 array([[231, 231, 231, ..., 192, 251, 255],
        [243, 245, 249, ..., 186, 149, 170],
        [187, 150, 170, ..., 209, 208, 198],
        ...,
        [186, 165, 187, ..., 158, 158, 146],
        [156, 156, 144, ..., 127, 171, 188],
        [161, 158, 177, ..., 245, 241, 227]], dtype=uint8),
 array([[ 73, 151, 218, ..., 230,  90, 171],
        [228,  91, 170, ..., 155, 212,  99],
        [154, 211,  98, ...,  30,  37,  46],
        ...,
        [204, 236, 183, ...,  30,  22,  29],
        [ 37,  30,  37, ..., 209, 136, 206],
        [205, 125, 203, ..., 203, 245, 158]], dtype=uint8),
 array([[255, 255, 255, ..., 194, 165, 187],
        [158,  73,  97, ..., 103,  84,  95],
        [117,  99,  95, ..., 121, 126, 117],
       

In [206]:
x=data+data1+data11

In [207]:
x=np.array(x)
x

array([[[ 57,  57,  57, ...,  67,  61,  58],
        [ 67,  61,  58, ...,  61,  70,  64],
        [ 61,  70,  64, ...,  62,  60,  66],
        ...,
        [ 68,  77,  71, ...,  76,  74,  80],
        [ 76,  75,  79, ..., 168,  67,  98],
        [151,  48,  74, ...,  71,  77,  73]],

       [[  0,   2,  29, ..., 245, 112, 231],
        [255,  85, 222, ...,   6,  31,   1],
        [  6,  31,   2, ...,   8,   5,  27],
        ...,
        [ 35,  70,  19, ...,  31,  45,  63],
        [ 30,  44,  63, ...,  82,  34,  56],
        [ 81,  27,  54, ..., 178, 231, 133]],

       [[ 12,  45,  30, ..., 114,  72, 104],
        [127,  79, 109, ..., 167, 136, 168],
        [151, 124, 191, ...,  63, 133, 103],
        ...,
        [ 18,  16,  35, ..., 235, 238, 253],
        [236, 239, 254, ...,  95,  49, 121],
        [ 98,  49, 123, ...,  77,  53,  51]],

       ...,

       [[ 64,  83,  58, ..., 146,  91, 125],
        [115,  70, 104, ...,  90,  73,  91],
        [135, 118,  81, ...,  50,  81,  72

In [208]:
x.shape

(60, 200, 200)

In [209]:
x=x.reshape(60, 200* 200)
x

array([[ 57,  57,  57, ...,  71,  77,  73],
       [  0,   2,  29, ..., 178, 231, 133],
       [ 12,  45,  30, ...,  77,  53,  51],
       ...,
       [ 64,  83,  58, ..., 118, 116, 122],
       [ 57,  69, 105, ...,  48,  67,  40],
       [ 73, 151, 218, ..., 203, 245, 158]], dtype=uint8)

In [210]:
x.shape

(60, 40000)

In [211]:
o=np.ones([20])
o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [212]:
i=np.zeros([20])
i

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [213]:
g=[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2]
g

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

In [214]:
y=np.append(o,i)
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [215]:
y=np.append(y,g)

In [216]:
y=np.array(y)
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [217]:
y.shape

(60,)

In [218]:
from sklearn.model_selection import train_test_split

In [219]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,shuffle=True,random_state=150)

In [220]:
from sklearn.linear_model import LogisticRegression

In [221]:
linear=LogisticRegression()

In [222]:
linear.fit(xtrain,ytrain)

LogisticRegression()

In [223]:
linear.predict(xtest)

array([2., 1., 2., 1., 0., 1., 2., 2., 2., 2., 2., 2.])

In [224]:
linear.score(xtest,ytest)

0.3333333333333333

In [225]:
from sklearn.tree import DecisionTreeClassifier

In [226]:
DTC= DecisionTreeClassifier()

In [227]:
DTC.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [228]:
DTC.predict(xtest)

array([0., 1., 0., 1., 0., 2., 2., 1., 2., 1., 2., 0.])

In [229]:
DTC.score(xtest,ytest)

0.3333333333333333

In [230]:
from sklearn.svm import SVC

In [231]:
support=SVC(kernel="poly",degree=6,C=1)

In [232]:
support.fit(xtrain,ytrain)

SVC(C=1, degree=6, kernel='poly')

In [233]:
support.predict(xtest)

array([2., 1., 1., 1., 0., 1., 0., 0., 0., 2., 2., 0.])

In [234]:
support.score(xtest,ytest)

0.5833333333333334

In [235]:
from sklearn.ensemble import RandomForestClassifier

In [236]:
random=RandomForestClassifier()

In [237]:
random.fit(xtrain,ytrain)

RandomForestClassifier()

In [238]:
random.predict(xtest)

array([0., 1., 1., 1., 0., 1., 0., 0., 2., 1., 1., 2.])

In [239]:
random.score(xtest,ytest)

0.4166666666666667

In [240]:
from sklearn.neighbors import KNeighborsClassifier

In [241]:
KNN=KNeighborsClassifier()

In [242]:
KNN.fit(xtrain,ytrain)

KNeighborsClassifier()

In [243]:
KNN.predict(xtest)

array([2., 2., 2., 2., 2., 2., 0., 0., 2., 2., 2., 2.])

In [244]:
KNN.score(xtest,ytest)

0.5

In [245]:
R={
    
    
    "Logistic_Regression":[linear.score(xtest,ytest)],
    "Decision_Tree_classifier":[DTC.score(xtest,ytest)],
    "Support_vector_Mechine":[support.score(xtest,ytest)],
    "Random_Forest_Classifier":[random.score(xtest,ytest)],
    "KNeighbors_Classifier":[KNN.score(xtest,ytest)]
}

In [253]:
R=pd.DataFrame(R).T
R

0
Logistic_Regression       0.333333
Decision_Tree_classifier  0.333333
Support_vector_Mechine    0.583333
Random_Forest_Classifier  0.416667
KNeighbors_Classifier     0.500000

In [254]:
from sklearn.metrics import accuracy_score

In [255]:
accuracy_score(ytest,linear.predict(xtest))

0.3333333333333333

In [256]:
accuracy_score(ytest,DTC.predict(xtest))

0.3333333333333333

In [257]:
accuracy_score(ytest,support.predict(xtest))

0.5833333333333334

In [258]:
accuracy_score(ytest,random.predict(xtest))

0.4166666666666667

In [259]:
accuracy_score(ytest,KNN.predict(xtest))

0.5

In [260]:
R["Accuracy_Score"]=[accuracy_score(ytest,linear.predict(xtest)),accuracy_score(ytest,DTC.predict(xtest)),accuracy_score(ytest,support.predict(xtest)),accuracy_score(ytest,random.predict(xtest)),accuracy_score(ytest,KNN.predict(xtest))]

In [262]:
R=R.rename(columns={0:"Score"})
R

Score  Accuracy_Score
Logistic_Regression       0.333333        0.333333
Decision_Tree_classifier  0.333333        0.333333
Support_vector_Mechine    0.583333        0.583333
Random_Forest_Classifier  0.416667        0.416667
KNeighbors_Classifier     0.500000        0.500000

In [263]:
from sklearn.metrics import confusion_matrix

In [267]:
cm1 = confusion_matrix(ytest,linear.predict(xtest))
sensitivity1 = cm1[0,0]/(cm1[0,1]+cm1[0,2])
print('Sensitivity : ', sensitivity1 )

Sensitivity :  0.0


In [268]:
cm1 = confusion_matrix(ytest,DTC.predict(xtest))
sensitivity2 = cm1[0,0]/(cm1[0,1]+cm1[0,2])
print('Sensitivity : ', sensitivity2 )

Sensitivity :  0.3333333333333333


In [269]:
cm1 = confusion_matrix(ytest,support.predict(xtest))
sensitivity3 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('Sensitivity : ', sensitivity3 )

Sensitivity :  0.75


In [270]:
cm1 = confusion_matrix(ytest,random.predict(xtest))
sensitivity4 = cm1[0,0]/(cm1[0,1]+cm1[0,2])
print('Sensitivity : ', sensitivity4 )

Sensitivity :  1.0


In [271]:
cm1 = confusion_matrix(ytest,KNN.predict(xtest))
sensitivity5 = cm1[0,0]/(cm1[0,1]+cm1[0,2])
print('Sensitivity : ', sensitivity5 )

Sensitivity :  1.0


In [273]:
R["Sensitivity_score"]=[sensitivity1,sensitivity2,sensitivity3,sensitivity4,sensitivity5]

In [274]:
R

Score  Accuracy_Score  Sensitivity_score
Logistic_Regression       0.333333        0.333333           0.000000
Decision_Tree_classifier  0.333333        0.333333           0.333333
Support_vector_Mechine    0.583333        0.583333           0.750000
Random_Forest_Classifier  0.416667        0.416667           1.000000
KNeighbors_Classifier     0.500000        0.500000           1.000000

In [275]:
cm1 = confusion_matrix(ytest,linear.predict(xtest))
specificity6 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity6)


Specificity :  1.0


In [276]:
cm1 = confusion_matrix(ytest,DTC.predict(xtest))
specificity7 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity7)

Specificity :  0.6666666666666666


In [277]:
cm1 = confusion_matrix(ytest,support.predict(xtest))
specificity8 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity8)

Specificity :  0.6666666666666666


In [278]:
cm1 = confusion_matrix(ytest,random.predict(xtest))
specificity9 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity9)

Specificity :  1.0


In [282]:
cm1 = confusion_matrix(ytest,KNN.predict(xtest))
specificity10= cm1[1,1]/(cm1[1,0]+cm1[1,2])
print('Specificity : ', specificity10)

Specificity :  0.0


In [283]:
R["Specificity"]=[specificity6,specificity7,specificity8,specificity9,specificity10]

In [284]:
R

Score  Accuracy_Score  Sensitivity_score  \
Logistic_Regression       0.333333        0.333333           0.000000   
Decision_Tree_classifier  0.333333        0.333333           0.333333   
Support_vector_Mechine    0.583333        0.583333           0.750000   
Random_Forest_Classifier  0.416667        0.416667           1.000000   
KNeighbors_Classifier     0.500000        0.500000           1.000000   

                          Specificity  
Logistic_Regression          1.000000  
Decision_Tree_classifier     0.666667  
Support_vector_Mechine       0.666667  
Random_Forest_Classifier     1.000000  
KNeighbors_Classifier        0.000000